name: khonology_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.0 # Added path_provider dependency
  shared_preferences: ^2.0.0 # Often used with path_provider, good to include
  provider: ^6.0.0 # Added provider dependency
  intl: ^0.18.0 # Added intl dependency
  file_picker: ^5.0.0 # Added file_picker dependency

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
